spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: root123
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: coupon-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false



  

    
 