spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: root123
  jpa:
   hibernate:
    ddl-auto: update
  application:
    name: product-server
    
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
server:
  port: 8082
  


      


      
      
    
      
      
    