spring:
  datasource:
   url: jdbc:mysql://localhost:3306/productcontroller
   username: root
   password: root123
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
     hibernate:
      format_sql: true
       dialect:org.hibernate.dialect.MySQL5Dialect
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        #exclude:
        #- health
      base-path: /myactuator      
  endpoint:
    shutdown:
      enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true

   