server:
  port: 2222

spring:
  datasource:
    password: root123
    url: jdbc:mysql://localhost:3306/zensar
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL5Dialect
  application:
    name: product-service-app




management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - beans
      base-path: /myactuator
      
      
  info:
    env:
      enabled: true
      
       
#info:
#  createdBy: srilaxmi
#  modifiedOn: 22ndjune2022
  

 
  
logging:
  level:
    com:
     zensar: debug
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka
      
  instance:
    prefer-ip-address: true
    hostname: localhost
        