spring:
 datasource:
  url: jdbc:mysql://localhost:3306/couponmanagement
  username: root
  password: root123
 jpa:
  hibernate:
   ddl-auto: update
   
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        #exclude:
        #- health
      base-path: /myactuator      
  endpoint:
    shutdown:
      enabled: true
  info:
    build:
      enabled: true
    git:
      enabled: true
    env:
      enabled: true
logging:
  level:
    com:
      zensar:
        coupon: debug
   