server:
  port: 1111
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/couponmanagement
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: coupon-service
    
   
        
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: /myactuator
      
      
  info:
    env:
      enabled: true
      
  
logging:
  level:
    com:
     zensar: debug
     
     
     